version: '3.5'

x-sqlite-db-dir:
  &sqlite-db-dir
  type: bind
  source: ./data/


services:

  frontend:
    container_name: frontend
    restart: unless-stopped
    image: frontend 
    build:
      context: ./service_frontend
      # target: ${FRONTEND_ENV}
    env_file: .env      
    volumes:
      - << : *sqlite-db-dir
        target: /app/data/
    secrets:
      - source: oidc_secret
        target: oidc_client_secret
        uid: 'uwsgi'
        mode: 0400
      - source: cookie_secret
        target: cookie_secret
        uid: 'uwsgi'
        mode: 0400

  reverse_proxy:
    container_name: reverse_proxy
    restart: unless-stopped    
    image: reverse_proxy
    build:
      context: ./service_rproxy
    depends_on:
      - frontend
      - certificate
    env_file: .env    
    volumes:
      - ./static:/var/www/web/
      - ./certificate/conf:/etc/letsencrypt
      - ./certificate/www:/var/www/certbot/
    secrets:
      - source: nginx_api_secret
        target: nginx_api_credentials
    ports:
      - "80:80"
      - "443:443"

  certificate:
    container_name: certificate
    restart: unless-stopped
    image: certificate
    build:
      context: ./certificate
    env_file: .env      
    volumes:
      - ./certificate/conf:/etc/letsencrypt
      - ./certificate/www:/var/www/certbot
    secrets:
      - source: nginx_api_secret
        target: nginx_api_credentials

  database_backup:
    container_name: database_backup
    restart: unless-stopped
    image: database_backup
    build:
      context: ./database_backup
    volumes:
      - <<: *sqlite-db-dir
        target: /workdir/

secrets:
  oidc_secret:
    file: ./oidc_secret.txt
  cookie_secret:
    file: ./cookie_secret.txt
  nginx_api_secret:
    file: ./nginx_api_credentials.txt
