version: "3.5"

services:
  frontend-app:
    #profiles:
    #  - disabled
    build:
      target: production

  backend_v1:
    build:
      target: production
    environment:
      FLASK_ENV: production
      GUNICORN_WORKERS: 1

  reverse_proxy:
    build:
      target: production
