version: '3'
services:
  flask:
    image: flask-eosc-perf
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # override app folder during development
    volumes:
      # production config
      - ./config.yaml:/app/config.yaml
      # access to database file
      - ./data:/app/data/

  nginx:
    image: nginx:1.14.2-alpine
    restart: unless-stopped
    depends_on:
      - flask
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./nginx/certs:/etc/nginx/certs
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/web/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot
    restart: unless-stopped
    build:
      context: docker/certbot
      dockerfile: Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file: .env
