version: '3'
services:
  flask:
    image: flask-eosc-perf
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # override app folder during development
    volumes:
      # production config
      - ./config.yaml:/app/config.yaml
      # access to database file
      - ./data:/app/data/

  nginx:
    image: nginx
    restart: unless-stopped
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - flask
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/var/www/web/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/
    env_file: .env

  certbot:
    image: certbot
    restart: unless-stopped
    build:
      context: docker/certbot
      dockerfile: Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file: .env
