version: "3.5"

services:
  frontend-auth:
    volumes:
      - ./service_frontend/:/app

  frontend-app:
    profiles:
      - disabled

  backend_v1:
    build:
      target: production

  reverse_proxy:
    build:
      target: production
    volumes:
      - ./frontend-js/build/:/var/www/web/
