version: '3.1'
services:
  flask:
    image: flask
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # access to database file
      - ./data:/app/data/
    env_file: .env
    secrets:
      - source: oidc_secret
        target: oidc_client_secret
        uid: 'uwsgi'
        mode: 0400
      - source: cookie_secret
        target: cookie_secret
        uid: 'uwsgi'
        mode: 0400

  nginx:
    image: nginx
    restart: unless-stopped
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - flask
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/var/www/web/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot/
    env_file: .env
    secrets:
      - source: nginx_api_secret
        target: nginx_api_credentials

  certbot:
    image: certbot
    restart: unless-stopped
    build:
      context: docker/certbot
      dockerfile: Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file: .env
    secrets:
      - source: nginx_api_secret
        target: nginx_api_credentials

secrets:
  oidc_secret:
    file: ./oidc_secret.txt
  cookie_secret:
    file: ./cookie_secret.txt
  nginx_api_secret:
    file: ./nginx_api_credentials.txt
