version: '3'
services:
  flask:
    image: flask-eosc-perf
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # override app folder during development
    volumes:
      # development mounts, if these do not change, they should be copied in the dockerfile
      - ./eosc_perf:/app/eosc_perf
      - ./templates:/app/templates
      - ./uwsgi.ini:/app/uwsgi.ini
      - ./upload_license.txt:/app/upload_license.txt
      # production config
      - ./config.yaml:/app/config.yaml

  nginx:
    image: nginx:1.14.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/web/
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot/
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - flask
